# Generated by Django 4.1 on 2025-01-23 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudenData",
            new_name="StudentData",
        ),
    ]
